# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class CompletedJobWebSocket:
        managementEndpoint: str
        type: str
        url: str
    class ConvertJobApi:
        type: str
        url: str
    class ConvertJobQueue:
        type: str
        url: str
    class ConvertJobsTable:
        name: str
        type: str
    class MediaBucket:
        name: str
        type: str
    class WsConnectionsTable:
        name: str
        type: str

