/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CompletedJobWebSocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "ConvertJobApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ConvertJobQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ConvertJobsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
